// import Image from "next/image";
import { Metadata } from 'next';

export const metadata:Metadata = {
  title: "Home page: Create Next App",
  description: "Generated by create next app",
}

export default function Home() {
  return (
    <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
      <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
        <h1 className="text-4xl sm:text-5xl font-bold tracking-[-.01em] text-center sm:text-left">
          Create Next App
        </h1>



        
      </main>
      
    </div>
  );
}
